name: release
on:
  push:
    tags:
      - v*
jobs:
  release:
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        node-version: 'latest'
      - name: Release
        run: |
          cd backend
          npm run publish
