name: release
on:
  push:
    tags:
      - v*
steps:
  - name: Check out Git repository
    uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    node-version: 'latest'
  - name: Release
    run: npm run publish
